# Generated by Django 4.0.1 on 2022-04-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_followers_following_pfpic_postpic_user_bio_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='fwerid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='following',
            name='fwingid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
