# Generated by Django 4.0.1 on 2022-04-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follows_remove_user_fllowers_remove_user_fllowing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
