# Generated by Django 4.0.1 on 2022-04-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Postpic',
        ),
    ]
