# Generated by Django 4.0.1 on 2022-04-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_user_pfp_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('postID', 'liker')},
        ),
    ]
