# Generated by Django 4.0.1 on 2022-04-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
