# Generated by Django 4.0.1 on 2022-04-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_remove_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
